package com.bstek.demo.ims.entity;

// Generated 2012-9-7 16:29:46 by Hibernate Tools 3.4.0.CR1

import java.util.Collection;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "ims")
public class Category implements java.io.Serializable {

	private Integer id;
	private String name;
	private String comment;
	private Collection<Goods> goodses;

	public Category() {
	}

	public Category(String name, String comment, Collection<Goods> goodses) {
		this.name = name;
		this.comment = comment;
		this.goodses = goodses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "comment", length = 200)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@OneToMany(fetch = FetchType.LAZY,mappedBy = "category")
	public Collection<Goods> getGoodses() {
		return this.goodses;
	}

	public void setGoodses(Collection<Goods> goodses) {
		this.goodses = goodses;
	}

}
