package com.bstek.demo.ims.entity;

// Generated 2012-9-7 16:29:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Goods generated by hbm2java
 */
@Entity
@Table(name = "goods", catalog = "ims")
public class Goods implements java.io.Serializable {

	private Integer id;
	private Category category;
	private Integer categoryId;
	private String name;
	private String birthplace;
	private String specification;
	private String packaging;
	private Integer sales;
	private Integer storage;
	private Integer totalStorage;
	private String comment;
	private Set<Sell> sells = new HashSet<Sell>(0);
	private Set<Purchasing> purchasings = new HashSet<Purchasing>(0);

	public Goods() {
	}

	public Goods(Category category, String name, String birthplace,
			String specification, String packaging, Integer sales,
			Integer storage, Integer totalStorage, String comment,
			Set<Sell> sells, Set<Purchasing> purchasings) {
		this.category = category;
		this.name = name;
		this.birthplace = birthplace;
		this.specification = specification;
		this.packaging = packaging;
		this.sales = sales;
		this.storage = storage;
		this.totalStorage = totalStorage;
		this.comment = comment;
		this.sells = sells;
		this.purchasings = purchasings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id",insertable=false,updatable=false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	@Column(name = "category_id")
	public Integer getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}
	@Column(name = "birthplace", length = 200)
	public String getBirthplace() {
		return this.birthplace;
	}

	public void setBirthplace(String birthplace) {
		this.birthplace = birthplace;
	}

	@Column(name = "specification", length = 100)
	public String getSpecification() {
		return this.specification;
	}

	public void setSpecification(String specification) {
		this.specification = specification;
	}

	@Column(name = "packaging", length = 100)
	public String getPackaging() {
		return this.packaging;
	}

	public void setPackaging(String packaging) {
		this.packaging = packaging;
	}

	@Column(name = "sales")
	public Integer getSales() {
		return this.sales;
	}

	public void setSales(Integer sales) {
		this.sales = sales;
	}

	@Column(name = "storage")
	public Integer getStorage() {
		return this.storage;
	}

	public void setStorage(Integer storage) {
		this.storage = storage;
	}

	@Column(name = "total_storage")
	public Integer getTotalStorage() {
		return this.totalStorage;
	}

	public void setTotalStorage(Integer totalStorage) {
		this.totalStorage = totalStorage;
	}

	@Column(name = "comment", length = 500)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
	public Set<Sell> getSells() {
		return this.sells;
	}

	public void setSells(Set<Sell> sells) {
		this.sells = sells;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
	public Set<Purchasing> getPurchasings() {
		return this.purchasings;
	}

	public void setPurchasings(Set<Purchasing> purchasings) {
		this.purchasings = purchasings;
	}

}
