package com.bstek.demo.ims.entity;

// Generated 2012-9-7 16:29:46 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Purchasing generated by hbm2java
 */
@Entity
@Table(name = "purchasing", catalog = "ims")
public class Purchasing implements java.io.Serializable {

	private Integer id;
	private Goods goods;
	private Producer producer;
	private Integer producerId;
	private BigDecimal totalPrice;
	private BigDecimal unitPrice;
	private BigDecimal totalnumber;
	private BigDecimal payout;
	private Date sellTime;
	private String comment;

	public Purchasing() {
	}

	public Purchasing(Goods goods, Producer producer, BigDecimal totalPrice,
			BigDecimal unitPrice, BigDecimal totalnumber, BigDecimal payout,
			Date sellTime, String comment) {
		this.goods = goods;
		this.producer = producer;
		this.totalPrice = totalPrice;
		this.unitPrice = unitPrice;
		this.totalnumber = totalnumber;
		this.payout = payout;
		this.sellTime = sellTime;
		this.comment = comment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_id")
	public Goods getGoods() {
		return this.goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "producer_id",insertable = false, updatable = false)
	public Producer getProducer() {
		return this.producer;
	}

	public void setProducer(Producer producer) {
		this.producer = producer;
	}

	@Column(name = "PRODUCER_ID")
	public Integer getProducerId() {
		return producerId;
	}

	public void setProducerId(Integer producerId) {
		this.producerId = producerId;
	}
	@Column(name = "total_price", precision = 20)
	public BigDecimal getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(BigDecimal totalPrice) {
		this.totalPrice = totalPrice;
	}

	@Column(name = "unit_price", precision = 9)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "totalnumber", precision = 9)
	public BigDecimal getTotalnumber() {
		return this.totalnumber;
	}

	public void setTotalnumber(BigDecimal totalnumber) {
		this.totalnumber = totalnumber;
	}

	@Column(name = "payout", precision = 20)
	public BigDecimal getPayout() {
		return this.payout;
	}

	public void setPayout(BigDecimal payout) {
		this.payout = payout;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sell_time", length = 0)
	public Date getSellTime() {
		return this.sellTime;
	}

	public void setSellTime(Date sellTime) {
		this.sellTime = sellTime;
	}

	@Column(name = "comment", length = 400)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
